### ISSUE TITLE
NullPointerException from Logz.io sender

### ISSUE THREAD

**Issue by MarinaRazumovsky** [logzio/logzio-java-sender#9]
java.lang.NullPointerException
at io.logz.sender.FormattedLogMessage.getSize(FormattedLogMessage.java:16)
at io.logz.sender.LogzioSender.sizeInBytes(LogzioSender.java:254)
at io.logz.sender.LogzioSender.dequeueUpToMaxBatchSize(LogzioSender.java:217)
at io.logz.sender.LogzioSender.drainQueue(LogzioSender.java:229)
at io.logz.sender.LogzioSender.drainQueueAndSend(LogzioSender.java:174)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
...

**Comment by MarinaRazumovsky** [comment]
Fix in version 1.0.5
#https://github.com/logzio/logzio-java-sender/pull/10
